[project]
name = "hass-template-climate"
version = "0.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "colorlog>=6.9.0",
    "homeassistant>=2025.8.0b0"
]
