name: "Release"

on:
  push:
    branches:
      - "beta"
      - "alpha"
  workflow_dispatch:

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup node"
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: "Install yq"
        uses: mikefarah/yq@v4.45.1

      - name: "Install semantic-release"
        run: >
          npm install -g
          semantic-release
          @semantic-release/changelog
          @semantic-release/exec
          @semantic-release/git
          @semantic-release/github

      - name: "Release Package"
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
